### ISSUE TITLE
Neorg not working - Doom is using unstable norg treesitter

### ISSUE THREAD

**Issue by molleweide** [NTBBloodbath/doom-nvim#110] opened 2021-09-05 19:10 UTC
in reference to this: https://github.com/vhyrro/tree-sitter-norg/issues/10

Is doom suppose to use the unstable norg treesitter branch?

I am asking because I have no idea myself but I noticed this when trying to problem solve
so I thought I'd ask.

**Comment by NTBBloodbath** [comment] 2021-09-05 20:02
Hey, we are using the main norg treesitter branch.

It seems to be a compiling issue, do you have the latest Doom Nvim version? Both branches, main (v3.1.1) and develop (v3.2.0-beta1) has the correct setup for the latest norg treesitter parser changes.

Regards

**Comment by NTBBloodbath** [comment] 2021-09-05 20:02
Hey, we are using the main norg treesitter branch.

It seems to be a compiling issue, do you have the latest Doom Nvim version? Both branches, main (v3.1.1) and develop (v3.2.0-beta1) has the correct setup for the latest norg treesitter parser changes.

Regards

**Comment by abzcoding** [comment] 2021-09-16 13:15
i had the same error on mac, which got fixed using this <https://github.com/nvim-neorg/neorg/issues/74#issuecomment-906627223>

**Comment by abzcoding** [comment] 2021-09-16 13:51
@molleweide you need to do this
```sh
brew install gcc
ln -s /usr/local/Cellar/gcc/11.2.0/bin/gcc-11 /usr/local/bin/gcc
```

**Comment by osamuaoki** [comment] 2021-09-26 08:29
treesitter/highlighter: Error executing lua: /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:161: query: invalid node type at position 7323 

I get this in devel branch setting of doom-nvim. I tried both unstable and main branch of neorg but the error occurs.
* NVIM v0.6.0-dev
* LuaJIT 2.1.0-beta3
* neovim is taged as 0.5.0.546.gc2a65921d
* OS is Debian testing
* GCC is 10
* LIBC is 2.32
* nodejs is 12.22.5

**Comment by NTBBloodbath** [comment] 2021-09-26 19:51
Hi, is your neorg up-to-date locally? `:PackerSync` should update both Neorg plugin and treesitter parser for it.

**Comment by osamuaoki** [comment] 2021-09-27 08:56
Yep latest  (well reinstalled from fresh for init.lua hacking.).
No rush for me for this one.  I have got plenty to play with :-)

**Comment by aovlllo** [comment] 2021-09-29 16:21
And also keybinds for neorg are not working. Could not figure out how to set them correctly

**Comment by NTBBloodbath** [comment] 2021-09-29 16:23
> And also keybinds for neorg are not working. Could not figure out how to set them correctly

Hmm right, I think I know what the issue is, gimme a moment

**Comment by osamuaoki** [comment] 2021-09-30 03:55
No problem now.  Please close this.

**Closed** 2021-09-30 04:51 UTC

**Comment by aovlllo** [comment] 2021-09-30 05:18
You are awesome, thx 😊
