### ISSUE TITLE
errors when opening dashboard commands

### ISSUE THREAD

**Issue by samrath2007** [NTBBloodbath/doom-nvim#38] opened 2021-07-12 12:37 UTC
```Error executing vim.schedule lua callback: ...scope.nvim/lua/telescope/previewers/buffer_previewer.lua:228: Vim(lua):E5108
: Error executing lua [string ":lua"]:1: attempt to index global 'Luasnip_current_nodes' (a nil value)```

**Comment by NTBBloodbath** [comment] 2021-07-12 12:46
Hey, it looks like an error caused by `LuaSnip`. Is it installed? You can check it by doing `:PackerStatus` and looking for a `LuaSnip` entry :thinking:

**Comment by bdillahu** [comment] 2021-07-12 13:26
Same error here... my :PackerStatus shows it loaded...

**Comment by NTBBloodbath** [comment] 2021-07-12 13:30
Alright so I've found that it's a bug or a breaking change because it works when downgrading `LuaSnip`. I'll dig on it a bit more before pushing changes here. I'll let you know when it's fixed here.

Thank you for reporting this!

**Comment by NTBBloodbath** [comment] 2021-07-12 15:27
Hey so I've uploaded a temporal fix for this behavior because a commit in `LuaSnip` broke the plugin (already reported it, let's wait for a fast fix).

So for temporarily fix this I have established that LuaSnip should use a specific commit (before the one that actually broke the code). The steps for fixing it will be:

1. Update Doom Nvim using `:DoomUpdate` command.
2. Remove the LuaSnip plugin (`rm -rf ~/.local/share/nvim/site/pack/packer/opt/LuaSnip`).
3. Launch Neovim to install `LuaSnip` again.

**Closed by NTBBloodbath** 2021-07-12 15:27 UTC
Labels: branch: main, bug

**Comment by bdillahu** [comment] 2021-07-12 15:32
I'll confirm that does seem to fix it...

**Comment by NTBBloodbath** [comment] 2021-07-12 16:35
Got some good news, L3MON4D3 (the `LuaSnip` dev) did a quick fix for this issue so I'm gonna revert the specific commit changes.
