### ISSUE TITLE
[BUG] Error when using Telescope shortcut

### ISSUE THREAD

**Issue by acherifi** [NTBBloodbath/doom-nvim#378] opened 2022-08-02 07:41 UTC
### Current Behavior:

Hi, 

When I try to use a Telescope shortcut like _Space ._ to browse through telescope project I get this error message
```
Error in packer_compiled: ...m/site/pack/packer/start/packer.nvim/lua/packer/load.lua:83: Vim:[telescope.run_command]: Unknown command                                                                                                                          
Please check your config for correctness 
```

### Logs

<details>
<summary>Check Health Output</summary>

nvim: health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: RelWithDebInfo

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=\177
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $COLORTERM='truecolor'

nvim-lsp-installer: require("nvim-lsp-installer.health").check()
========================================================================
## nvim-lsp-installer report
  - OK: neovim version >= 0.7.0
  - OK: **Go**: `go version go1.18 linux/amd64`
  - OK: **cargo**: `cargo 1.60.0 (d1fd9fe 2022-03-01)`
  - WARNING: **luarocks**: not available
  - OK: **Ruby**: `ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [x86_64-linux-gnu]`
  - OK: **RubyGem**: `3.3.5`
  - WARNING: **Composer**: not available
  - WARNING: **PHP**: not available
  - OK: **npm**: `8.11.0`
  - OK: **node**: `v16.16.0`
  - OK: **python3**: `Python 3.8.13`
  - OK: **pip3**: `pip 22.0.4 from /home/acherifi@fr.idmog.com/.local/lib/python3.8/site-packages/pip (python 3.8)`
  - WARNING: **javac**: not available
  - OK: **java**: `openjdk version "11.0.15" 2022-04-19`
  - WARNING: **julia**: not available
  - OK: **wget**: `GNU Wget 1.21.2 built on linux-gnu.`
  - OK: **curl**: `curl 7.81.0 (x86_64-pc-linux-gnu) libcurl/7.81.0 OpenSSL/3.0.2 zlib/1.2.11 brotli/1.0.9 zstd/1.4.8 libidn2/2.3.2 libpsl/0.21.0 (+libidn2/2.3.2) libssh/0.9.6/openssl/zlib nghttp2/1.43.0 librtmp/2.3 OpenLDAP/2.5.12`
  - OK: **gzip**: `gzip 1.10`
  - OK: **tar**: `tar (GNU tar) 1.34`
  - OK: **bash**: `GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu)`
  - OK: **sh**: `Ok`
  - OK: GitHub API rate limit. Used: 0. Remaining: 60. Limit: 60. Reset: mar. 02 août 2022 10:39:59.

nvim-treesitter: require("nvim-treesitter.health").check()
========================================================================
## Installation
  - WARNING: `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)
  - OK: `node` found v16.16.0 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
    Version: cc (Ubuntu 11.2.0-19ubuntu1) 11.2.0
  - OK: Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I J
  - c              ✓ ✓ ✓ ✓ ✓ 
  - bash           ✓ ✓ ✓ . ✓ 
  - lua            ✓ ✓ ✓ ✓ ✓ 

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}

provider: health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: xclip

## Python 3 provider (optional)
  - INFO: `g:python3_host_prog` is not set.  Searching for python3.10 in the environment.
  - INFO: Multiple python3.10 executables found.  Set `g:python3_host_prog` to avoid surprises.
  - INFO: Executable: /usr/bin/python3.10
  - INFO: Other python executable: /bin/python3.10
  - INFO: Python version: 3.10.4
  - INFO: pynvim version: 0.4.2 (outdated; from /usr/lib/python3/dist-packages/neovim)
  - WARNING: Latest pynvim is NOT installed: 0.4.3

## Python virtualenv
  - OK: no $VIRTUAL_ENV

## Ruby provider (optional)
  - INFO: Ruby: ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [x86_64-linux-gnu]
  - WARNING: `neovim-ruby-host` not found.
    - ADVICE:
      - Run `gem install neovim` to ensure the neovim RubyGem is installed.
      - Run `gem environment` to ensure the gem bin directory is in $PATH.
      - If you are using rvm/rbenv/chruby, try "rehashing".
      - See :help |g:ruby_host_prog| for non-standard gem installations.
      - You may disable this provider (and warning) by adding `let g:loaded_ruby_provider = 0` to your init.vim

## Node.js provider (optional)
  - INFO: Node.js: v16.16.0
  - WARNING: Missing "neovim" npm (or yarn) package.
    - ADVICE:
      - Run in shell: npm install -g neovim
      - Run in shell (if you use yarn): yarn global add neovim
      - You may disable this provider (and warning) by adding `let g:loaded_node_provider = 0` to your init.vim

## Perl provider (optional)
  - WARNING: "Neovim::Ext" cpan module is not installed
    - ADVICE:
      - See :help |provider-perl| for more information.
      - You may disable this provider (and warning) by adding `let g:loaded_perl_provider = 0` to your init.vim

telescope: require("telescope.health").check()
========================================================================
## Checking for required plugins
  - OK: plenary installed.
  - OK: nvim-treesitter installed.

## Checking external dependencies
  - OK: rg: found ripgrep 13.0.0
  - OK: fd: found fd 8.3.1

## Telescope Extension: `mapper`
  - INFO: No healthcheck provided

## Telescope Extension: `projects`
  - INFO: No healthcheck provided

vim.lsp: require("vim.lsp.health").check()
========================================================================
  - INFO: LSP log level : WARN
  - INFO: Log path: /home/acherifi@fr.idmog.com/.cache/nvim/lsp.log
  - INFO: Log size: 20495 KB

vim.treesitter: require("vim.treesitter.health").check()
========================================================================
  - INFO: Runtime ABI version : 14
  - OK: Loaded parser for bash: ABI version 13
  - OK: Loaded parser for lua: ABI version 13
  - OK: Loaded parser for c: ABI version 13

which_key: health#which_key#check
========================================================================
## WhichKey: checking conflicting keymaps
  - WARNING: conflicting keymap exists for mode **"n"**, lhs: **"gc"**
  - INFO: rhs: `<Cmd>lua require("Comment.api").call("toggle_linewise_op")<CR>g@`

</details>

<details>
<summary>Doom Report Output</summary>

I cannot launch DoomReport because of this error 
![image](https://user-images.githubusercontent.com/19311305/182319754-7427f2a4-5eb6-448f-9b57-31f618a759ab.png)

</details>

**Comment by connorgmeehan** [comment] 2022-08-02 09:17
Thanks for the issue, I've been meaning to sort out the `Telescope find_files` issue.  This bug is caused by the `Telescope file_browser` command being moved to its own package. https://github.com/nvim-telescope/telescope-file-browser.nvim.  I'll sort it out later this week hopefully :)

**Comment by connorgmeehan** [comment] 2022-08-12 04:21
This is resolved in https://github.com/NTBBloodbath/doom-nvim/commit/845b5b6423bf54a5f3347363ec2f6dc097086c68

**Closed by connorgmeehan** 2022-08-12 04:21 UTC
Labels: scope: bug, good first issue
