### ISSUE TITLE
Theme not being found in path

### ISSUE THREAD

**Issue by bdillahu** [NTBBloodbath/doom-nvim#42] opened 2021-07-12 17:52 UTC
This may very well be an issue of not understanding the config, but I changed the default theme in doom_config.lua to be doom-nord - it seems to have downloaded the theme files in ~/.local/share... but it can't seem to find what it's looking for.

![Screen Shot 2021-07-12 at 13 52 29](https://user-images.githubusercontent.com/2058566/125333600-6d747100-e318-11eb-948a-61dfe4468e95.png)

**Comment by NTBBloodbath** [comment] 2021-07-12 17:58
Hey, thank you for reporting this. I think I know what's happening here, give me a moment to fix it :slightly_smiling_face:

**Comment by NTBBloodbath** [comment] 2021-07-12 17:59
Alright, should be fixed now. Remember to update and if the issue is still here do `:PackerCompile` and restart Neovim.

Regards

**Comment by NTBBloodbath** [comment] 2021-07-12 18:00
@all-contributors add @bdillahu for bug reporting

**Closed** 2021-07-12 17:59 UTC

**Comment by bdillahu** [comment] 2021-07-12 18:03
That fixed it...
